export type PopContainerPropsTrigger = 'hover' | 'click'
export type PopContainerPropsPlacement =
  | 'top-start'
  | 'top'
  | 'top-end'
  | 'right-start'
  | 'right'
  | 'right-end'
  | 'bottom-start'
  | 'bottom'
  | 'bottom-end'
  | 'left-start'
  | 'left'
  | 'left-end'

export type PopArrow = 'top' | 'right' | 'bottom' | 'left'
export type PopSubFlag = 'popover' | 'popconfirm' | 'dropdown'
